// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTexbS3Xa_iCdt0vezii9t1io7-_XUf9s',
    appId: '1:438155285660:web:6ae40dc88f7af992944959',
    messagingSenderId: '438155285660',
    projectId: 'urbanswiftdelivery-532fd',
    authDomain: 'urbanswiftdelivery-532fd.firebaseapp.com',
    storageBucket: 'urbanswiftdelivery-532fd.appspot.com',
    measurementId: 'G-7Z11GV3CSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfvkhN7VSJjB6-Ty9xRzlGNNQhntWPWQQ',
    appId: '1:438155285660:android:1018051faef37689944959',
    messagingSenderId: '438155285660',
    projectId: 'urbanswiftdelivery-532fd',
    storageBucket: 'urbanswiftdelivery-532fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC76yQuFxlJsij7euGUm51Rzzce7JLUIg4',
    appId: '1:438155285660:ios:882af26bfdc7f68c944959',
    messagingSenderId: '438155285660',
    projectId: 'urbanswiftdelivery-532fd',
    storageBucket: 'urbanswiftdelivery-532fd.appspot.com',
    androidClientId: '438155285660-tlq7gglg311tngk5c9083ek7kqrn43u5.apps.googleusercontent.com',
    iosClientId: '438155285660-7f0phq03tn2b3q6mmu8nod18s8j79h61.apps.googleusercontent.com',
    iosBundleId: 'com.example.pingoLearnPractical',
  );
}
