// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVKtI4Lfkh54-QLOAXKCDpi98drEmHms0',
    appId: '1:510408589992:web:7619532db6652efec2389d',
    messagingSenderId: '510408589992',
    projectId: 'test-project-f55d4',
    authDomain: 'test-project-f55d4.firebaseapp.com',
    storageBucket: 'test-project-f55d4.appspot.com',
    measurementId: 'G-5T3JSCC6G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMa_LgJDcp4F9ZqUY5Ai9l9Dlm9iGpxYg',
    appId: '1:510408589992:android:109df600b25b3e9fc2389d',
    messagingSenderId: '510408589992',
    projectId: 'test-project-f55d4',
    storageBucket: 'test-project-f55d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYnDT04rq8hZntHg2eaKOFdkdkd2U9NDM',
    appId: '1:510408589992:ios:a57db2a5b3834e80c2389d',
    messagingSenderId: '510408589992',
    projectId: 'test-project-f55d4',
    storageBucket: 'test-project-f55d4.appspot.com',
    androidClientId: '510408589992-1pj2sb0ope0heb1j0p2puvf9uannlgpk.apps.googleusercontent.com',
    iosClientId: '510408589992-3ecgnhcam5jamig70hs29i6k20pivm4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.pingoLearnPractical',
  );

}